### ISSUE TITLE
How to stop bad code from being executed?

### ISSUE THREAD

**Issue by bennycode** [tapjs/tsimp#13]
I have written this code (which leads to `error TS6133: 'MyClass' is declared but its value is never read`):

```ts
import {MyClass} from './MyClass.js';

console.log(`Hello, World!`);
```

When I executed this code using `node --import=tsimp/import ./src/start.ts`, I get to see:

>  import {MyClass} from './MyClass.js';
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Hello from directory

Is there any way to prevent the execution of the `console.log` statement and instead just throw an error (due to the broken code)?

**Comment by bennycode** [comment]
@isaacs do you know how I can stop `tsimp` from executing the code if it is broken? My current workaround is `npx tsc --noEmit && node --import=tsimp/import ./src/start.ts` but I guess that defeats the purpose of having type checking as part of `tsimp`?

**Comment by isaacs** [comment]
You can set `TSIMP_DIAG=error` in the env to crash on any errors or warnings.

**Comment by bennycode** [comment]
Thank you for pointing me to it! 🙂 I am using `tsimp` now in my TypeScript starter template: https://github.com/bennycode/ts-node-starter/pull/639 ✌️🎉
